import { React, useEffect, useState } from "react";
import { connectWallet, getCurrentWalletConnected, mintNFT, upload2DDC, downloadFromDDC } from "./actions.js";

const Main = (props) => {

  //State variables
  const [status, setStatus] = useState("");
  const [walletAddress, setWalletAddress] = useState("");
  const [metadata, setMetadata] = useState("");
  const [cid, setCid] = useState(null);
  const [qty, setQty] = useState(null);
	const [uploadData, setUploadData] = useState(null);
  const [uploadDataTitle, setUploadDataTitle] = useState("")
  const [uploadDataDescription, setUploadDataDescription] = useState("")
  // For ddc download
  const [image, setImage] = useState(null);
  const [preview, setPreview] = useState(null);
  const [file, setFile] = useState(null);


  function addWalletListener() {
    if (window.ethereum) {
        window.ethereum.on("accountsChanged", (accounts) => {
          if (accounts.length > 0) {
            setWalletAddress(accounts[0]);
            setStatus("Follow the steps below.");
          } else {
            setStatus("Connect to Metamask using the top right button.");
          }
        });
    } else {
        setStatus("Please install metamask and come back");
    }
  };

  useEffect(async () => {
    const {address, status} = await getCurrentWalletConnected();
    setWalletAddress(address)
    setStatus(status); 
    addWalletListener();
  }, []);

  const connectWalletPressed = async () => {
    const walletResponse = await connectWallet();
    setStatus(walletResponse.status);
    setWalletAddress(walletResponse.address);
  };

  // Functions to fill out
  const onMintPressed = async () => {
    const { status } = await mintNFT(+qty, metadata)
    setStatus(status);
  };


  async function digestMessage(message) {
    const msgUint8 = new TextEncoder().encode(message);                           // encode as (utf-8) Uint8Array
    const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);           // hash the message
    const hashArray = Array.from(new Uint8Array(hashBuffer));                     // convert buffer to byte array
    const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join(''); // convert bytes to hex string
    return hashHex;
  }
  
  const onUploadPressed = async () => {
    console.log('uploadData', uploadData.data);
    // digestMessage(uploadData)
    // .then(digestBuffer => console.log(digestBuffer));
    // digestMessage(uploadData)
    // .then(digestBuffer => {
    // })
    const { contentId, status } = await upload2DDC(uploadData, uploadDataTitle, uploadDataDescription);
    //console.log(uploadData);
    setStatus(status);
    //console.log(file);
}


  const content2url = (content) => {
    //var base64 = content.toString('base64')
    //var base64 = btoa(unescape(encodeURIComponent(content)));
    var base64 = btoa(content);
    //var url = "data:image/png;base64," + (base64)
    var url = "data:image/png;base64," + (base64)
    console.log('urll', url);
    return url
  }
  
  const content2url2 = (content) => {
    const dummy = 'iVBORw0KGgoAAAANSUhEUgAAAFgAAABSCAYAAADQDhNSAAAABHNCSVQICAgIfAhkiAAAFN5JREFUeJztnHl0FFW+xz/VS3rLTkJ2EkICIWEzgICIw8Ao6KCo4zDKuM04bqjPJyLqoAj6VBREHcVtBnXUcUMU3BVUhFFQQJEQkwhJyJ6Qfe10ernzRzVFd9JJukOKd857+Z6Tc6qr7vKrb27d+t3f73tLSk1NFQxBNWj+tw34v44hglXGEMEqY4hglTFEsMoYIlhlDBGsMoYIVhlDBKuMIYJVhu6UdxgaTsSkGZjiRoBGg62umtZfDtFRcliV/szJaYSMHo8hKhZcLqxVpTQe2I2jpUmV/rrjlBGsMZpJ/fPtxJ27CI0+qMd1a3U5NdvepfLDN7A3N5xUX/rwSOJ/exkxZ1+MKTaxx3WXvYuqT96m6MXHcHV2nFRf/UE6FcEeXXAoEx95heBRY/st6+y0UrHlFUrfeg6nNbCb15rMjPjDDSRceCVao6nf8m2Fefx011U4WpsD6icQnBKCx61+jmHTfg2AEIKW3P005exFOJ2YEpKJmDidoMhorzq2ump+eeo+Gr7b4VcfkdNmM/qW1fJU4IYQAntjHY0/7cFaUYKk1RI+fiphWZNBkgCo/24Hh+67fnBu1AdUJzhy6q8Y/8ALAAiXk/x1d3Hsy/e7WaEhcsoskhZdR/j4KcppIQRVH79F4fMP4eqy+Wxfozcw6oa/EnfeH5DcpAkhaD60n7K3X6Bh3y4QLq86w+dcQMayNUgaLQA5K6+j4fuvB+uWvaCNiIhYpUrLbqQtuRdTfDIIQfm7L1O++UUfpQTWyhJqtr1LW2EeoZmnobOEIEkSIaPHETnlLBr27cTZ0eZVyxAdx4SHXiRq+hwkSUIIga22ioLH7qL4xXVYK0uAnuOnvbgArclCWGY2APqQ8J7/9EGCqm6a1hxM+KQZALicTsre+Ue/dep3f8G+6xdQ/fm7IGRyQtKzyH5yE8Hp45RywenjyH5yEyHpWYA8amu2vce+6xdQv/uLfvspe2cjLocDgPBJM9CagwO+P3+gKsGhYyag0cmOSkv+AexN9X7Vc1rbKVh/N/nr71amhqDIaCY9+grhp51B+GlnMOnRV5R529llo2D93RSsvxuntd2vPuxN9bTkHwBAo9MROmZCoLfnF1R108wjRinHbYdzA65fs+09OsqKGbfqGYLCh6E1WRi/+jkANEEGALqa6sldtUQhKxC0HT5E+Lgpiq2NP34bcBv9QdURHBQ5XDnuPFY5oDZa8w9wYOlldFaXAzKxx8ntrC7nwNLLBkSubFOVT1sHE+rOwSazctz9BRUIrJUlFL20vsf5opfWu19kA4OnTZ62DibUjUW43SZAeWENBObkdEbfsqrH+dG3rMKcnD7gdr1s8rR1EKEqwZ6+q9Y4sBESFBHF+AdeQBccCoCtoRZbQy0grxDHP/AC+oioAbXtOWp787NPFqoS7LkE1YdFBFxf0geRtXIDxuHxcnvtbeSs+As5K/6Co11+vI3D4xm3cgOSj/hGf9CHnrBJreWyqgTb6muUY0N0bB8lfSP9ppWEjp0EgHA6+PnBW2kvzqe9OJ+fH7wV4ZT92NCxk0i/6b6A2/e0ydPWwYSqBB9/8wPyai4AxM67hLj5vwfkRUTh82to/OHfyvXGH/5N4QtrlN9x8y8hdt4lAfVhik9R2ve0dTChKsEdZYXKsTnF/5eROSWdtCX3Au4V2vYtVLz/ao9yFVtfpXrbe8rvtCX3BthPmk9bBxOqLjTsTQ3YGmoxREajDw7DGJtEZ3VZr+X1YZEYomLIuGMtWoNRPuly4WhvYdT1f0XS6ZE08pgQLhfCYcfR3opwOpG0WrQGI5l3PU7+2juw1dX0GVc2xiahDw4DoKuxDnvTycWge4PqAffWX3IwTJ8DyHNl57EKzEmjCB41FktKOuakUZgSkjHGJKA19IzhSlotiRde5Xd/lpR0Jm/YAoDTZqWzpgJrRQkdZYW0Hz1MW2EeHWWFytx+3Ea1oHq4MmnRtaT+eRkgu1g6k0U1p95fOK0dOKztGNyxjKKN6yjb9HdV+lKFYI3RxLDpc4ieeQ4Rk89E10+kSgihxHKPo6Ugh5bc/TjaW3F2duDqsuGyd52I7UoaNPogNEEGtEYzOksIoVmTCR0zvs92fcHR0Ubj/n9T+83n1O/5ElenNfCb7gWDSnDI6PHEL7iM6Fnz0ZosPsscf2O3HcmlrSifjtIjdJQfJeH8xcQvWAyAvbmRvdedF3BuTh8WydQXPlZ87soP36Dig39hTkzBPCKd4NQxBKdlYYxN7JV4p7Wd2l2fUvnhG4MydQwKwRHZM0levISwcVN6XBNC4LJ1Kjmyo6/8jZLXN3iVsaRmMPmpzUhaHUII8tcuH3AAfPicCxi7fK3ct9PB/lt+R3tRvleZ5MU3kXLlfwFyDlBrMPpcKjcf2kfJ68/Q+MM3A7IFTjKjYUpMJfOux0i5/BZltQUyqW2FeVS8+xKHn15N6+EcomfNB0BjMFL96SavdrLufQpjTAIAjft2UfziuoGaRHtxAaFjJmJKSEbSaLCMHEP1Z5u9yqRecweGqFj5n7luOUUvPkZXXTW60AhlXgZ5lRgzdyFhmZNpKcjB0dIYsD0DHsGJF1/NyKuXKqFDAKetk5ovtlL54eteo0ZrsjDjzW/RGowIIfj+T2cr7prniHPaOtl3/W9P2uk3xiYy5fmPFFcv79E7lCfCGJvE6S9tQ5IknLZOdl96hleQ3pKaQfyCxcTMXXjCVUSOVRS/vJ7yd18OyJaAR7Ck0zN2+VqSfncNklb28lz2Liref5Wf/+dWar/+CHtjnVcd4bDLbllyGpIk4WhtpjnnezQGI+PuewadJRghBKVvPkf9t9t9G2qyEDVjLtGz5hE+4XSCwodhq61COOw9yjraWpC0OsInTgMgdPQEKj9+E+F0kLDwSiLc5+t3b+8xFdkb62j47iuqPn0HSaslOC0TSatF0uqInDwLc+JI6vd8BS5Xj3592h0QwRoNWfc8pTzucvZ2Hzn3XMuxrz7sU8ThsncxfPYCAAwxCVRsfZWk319L1Bm/AeQ0fd7DS5X4gicSLrqKcaueJWbuQsInTiN84jSizzqX+PMX47J30eoj4N5acJCYuReis4SgswTj6rLRnLufMUsfRh8cihCC4pfWYy0v9m1vZ4fsWez8BEtqhjKFWVJGYxk5htpdn/gVgg2I4JQrbyX+3EWATG7Zpr+Tv+5Ov+amzqoy4s5dhNZkQR8cirXiKCOvvg1NkAEhBEc23E/bkZ5ppfSbV5G8eInXVHQcmiADkVNmERQeRcP3O7yuCacDe3MD0TPPAeTEqe1YFXHz5XiFvbGOw0+v7pHS7w5HaxM1X2xBow8iNDMbSZIwJ6UiabQ0/bSn3/v2m2BT4kgy73oMSaNBCMHRV56k5NW/+R9IFy70oeGKpzHs9F8pC472onyOPHN/jyrDZy8g9c+399t0yOjxWMuP0n70F6/z7Ud/IWrGXIIio9EEGRh2+q+Uaa1i62s0/uindyAETT/uRricREyaDkBY5mkc2/lJvxo3v4M9CQuvUIxr3LeL0jee9beqgsqP30I4nXLH7hEphKD4n4/7/EclL17id9s+ywpB8cuPKz+VPp1OKj9+MxDTASh941nq98oCFUmrI2HhFf3W8ZvgiOyZsnFCUPLGMwEbB2CrqaBuj7dmoTX/J5+qGmNskldWuj+YR4zC6EPo17D3a1ryvOfouj1fYBtgEtZzYB3npC/4TbAxOk45bi0Y+Aqn8oPXvX6XbfItRjEMj/N5vi8YPHzxvvrobkMgaC3IQbifNmO07/484TfBTvf6XJIkdCFhAzQPgtMyvX6HZEz0Wc5l6wyoXXnF6DuG0L2PkLSsgNr2hC4kTFlmO/2QvvpNcFtRnnJ83N0KGBotCRd4z1sJ5y9GHxbZo2h7yeGAEpHC3kV7yZEe5/VhkSScv9jrXPwFl4Nb+Bcohs/+rXLsyUlv8JvgY19+oBwn//EmjDE957v+EDVjDsZuj77WZCFp0XU9yro6rRz7+iO/2z729Uc+o2BJi67rEXgyDo8jasYcv9tW6sUkkvzHmwH5ifHkpDf4TXDNF1tod8v89SFhTHhoY69zXm+IO+9S5bjxwG7lOOH8xT7bKn5pPV3dVoW+0NVYR7EPYYohOk4ZvUIIrz49bfEHhuHxTHhoI3r39NhReoSaL7b0W89vgoXTSd6a2xXVuSkhhewnN/n1JgV59RZx2hkAuBx28h9ZRtPB72UjggyMvPq2HnW6Gmo5uOIaOmurelwDd+iztoqDK66hy62V8IRnrKQ5Zy/5jyzD5V5aR5x2Bgb36qw/RGTPJPvJTZgSUgA5YJ+3ZpnicvaFgFZy9qZ6Wn45SPSZ89Do9GhNZobPuQBjbCKtBT/1KflPWHgFEW4pa/2eL6n+7B06SguJnf97JEnCkpJOw75ddHVLn9sb66j+7B1cXTb04cPQh4aBEHSUFlH5wb/IX3unT5crZMwE0m5coeiG8x6+DWt5MSFpmZiTRiFJEvbWJppz9vZqc1BkNGlLVpJ67Z3o3NOMs9PKofuX0Jrnnx5uQNG04PQssu592itE6ey0Uvnxm1S8909sPkbc1L9/gjkpFSEEufffpGh4M+5cR8yvzwegpeAgP/73or5XhxqNfL2vMpLEaU+8rUhSa776gPxH5LTVsBlzGXef7Md3lBWx99pze1Q3RMeRcNFVxJ93qRLHPi7uzn3g5oCUogNK27cdzmX/jQup3vae4hNqjSaSLv4T017eTtbKDQybPhdJpwfAMnIM5qRUQI50NezdqbRVvHGd4u6EjplA3PxFfXfucvW7PI+bv0gh19nZQfHGE/Hlhr07sbtVPOakVCwjxwBylHDY9LlkrdzAtJe3k3Txn7zIrdm+hf03LgxYhnvSGY3QrMmkXrNMkeN7wt7WQsN3X6EJMigRuOrPN1Ow/q9e5UZcej0jr14q12ltltNFfrzcfEEfESWnjULC5JjJy49T+tbzXmXGLH2I2HN+B0Dtrk9xddmInPZr9G7923EIIWjJ+5Gijetoyd0/IHtOeo+GrbaK6s8203xoP/rQCExxIxRHXBtkIDg1A0vyCYFHV2O9PC+6nPJIEoKW/INEnTmPoLBItAYjxthEand+MiB7MpatUbYVdJQVkb/uTnnUa7SYR4wicsosQjOzFaWRJTmN4NQMtB7ROuFy0bB3J4efXsXRfz7hc8rzF4OeVTbGJBLzmwsZPnsB5qSRfZZ1dXXRUVGMtbwYXXCo4mUA5D92N3XffC5nG/qL2EmSHJCfeTYZt5+QUzX++C2OthZMiSMxJ4xEE9S7QFAIgbW8mGM7PqJm+3t01lT4d8P9QFVdhDklneRLb/Ra/QQK4XLhsllxdtkQdjvCJbtGkkaLpNejDTKgMZgUxc9AcGzHR5S8+SwdRwd/O6+qyp6Oo4ext56Il1Z9uglrZSkh6VkEj8qU0+f9ECNpNGhNll5lAP5AuL2Ozupy2gp/pvVwLqb4EYq40N7apAq5cAqkU6EZbvmp+03cfGifck1jMGFOTMGUkIIxJhHD8DgMUbEMO302klar1OsPnhoH4XRS//0ObHXV2I5V0VlTjrXiKB3lR72CQWHjpigEH7dRDahKsKTTYUkZLf9wuWjt5uK4bFbaCvNoK/QOmiRffgspl9+s1MtZeT0t+QfQ6PUguUe8cOGy2wkdO4nxq59H0mrdsepnKXntqX5taz2cq4gGLSmjkXQ6hKNnPvBkoap81ZQwUiYFeSNLb+HE7ih5fYOyjJa0WjKWrUFnsmBvasDeWCf/NTWgM1nIuH2NMtqbc/b2ELX0BpfNqmyg0ej1mBL6fiEPFCoTfEJ03VFW5H9Fl4u8NUuV+EJQRBRZ921A46FT0BiMZN23gSD3/oyuhlry1iz1O50O0FF+wiZPWwcTqhLsmQXprAlMTNLVUEvug7cqwZmQ9HFkLF8rS5wkiYw71hLi3lrrctjJffBWnwGfvtBZdcImT1sHE6oSrA8fphwHevMALbn7OfL0/YofHD3zHNJuWEHaDSuIPlNOxx9P+Q9kpdXVeMImT1sHE6q+5HTmE66Vo611QG1Uffo2psQUki65BsArkyuEoHzzi1R98vaA2na0n7BJax64G9gX1N2IqD3x/3M5e0qc/EXRxrUc2/Gh1zkhBLVff0zRxrUDbtdTdiVp1RlrqhIs7CduwNd3evxvSNDRTeIkSZL8kjqJHaSee+uEvWvA7fQFdTfBeEiqgsIGOMdJEqOuu4vEi67ucSnl8lvQWULk7VwDINrTJrtKX6FSlWDPgMnxeHAg0BjNZNzxiKIvE0LQuG8XAJFTzwIg8aKrMQxPIH/t8oC/IOVp02AFd7pD1Smi7cjPynHY+KmA/xuuzUmjyH7ibS9ya3d8xKHVSzi0eonXnBw982yyn3gbc5L/SiAkyW2TWzDuYetgQt2NiKVHsNVVA2CIiiFi8pn9V5I0JCy8guynNmNxbyoUQlD61vPkPboM4bAjHHbyHllGyZvPKbEKS0o62U9tlr0Mqf/bisg+E0NUDABd9TV0lPbUVAwGVP8oki40QvmqSHB6JjXbt/oUTQOET5xO5ooniJt3CRp3usnR0U7BuuVUbu2507PpwB46ygqJmDxL3nGk0xM59SyGTZuNtbK018WN1mQh854nCXILXiref42mA/1LUQcC1ffJ6cMiOX3jZ8rnCNoK8yj8xyM05+xDuJyYYpOIyJ5JzNkXeX03RwhBa8FB8h+9o9+Pbpjik8lYvpbQbhKploKD1Gx7j8YfvsFaXYak0RI2fiqj/rJc+Uieo62F76+Zd9JfG+wNp+TDdNGz5jP27se9Yr/HY7S+4sGO9laOvvY0FVtf8T+2oNGQsPBKUi6/GZ0lpMdl4XKBJHmHNl0u8h6+jdpdnwZ+U35C9SkC5LnYWl1O5OQzlUdf6n6zQuC0tlOx9VXyHr6NpgO7A3O9hKA1/wDVn70DkoQlZbSX7929P2enlYIn7qF2h//yrIHglIzg4zBEx5Fw4VVETj1L/vqqJNFVX0PrLznUf7eDum8+C/h7lb1BazITNXMew6bNJmT0eIKGxYAQWKtKadi7k4otvvUbg41TSvD/Rwx9oFllDBGsMoYIVhlDBKuMIYJVxhDBKmOIYJXxH4r7WLwgFoGBAAAAAElFTkSuQmCC';
    //return `data:image/jpeg;base64,${dummy2}`}
    const dummy2 = 'JUVGJUJGJUJEUE5HJTBEJTBBJTFBJTBBJTAwJTAwJTAwJTBESUhEUiUwMCUwMCUwMGclMDAlMDAlMDAlMUQlMDglMDMlMDAlMDAlMDAlRUYlQkYlQkQlMjYlRUYlQkYlQkRsJTAwJTAwJTAyJUVGJUJGJUJEUExURSUwMCUwMCUwMCUyMyUxRiUyMCUyMyUxRiUyMCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRDMlMjIlMjIlMjMlMUYlMjAlNDAlNDAlNDAlMjQlMjAhJTJCJTIwJTJCJTI2JTI2JTI2JTJDISElMjYlMjIlMjIlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlMjMlMUYlMjAnISEtLS0lMjQlMUYlMjIpKSklMjQlMjAhJTI0JTFGISUyNCUxRiE5OTklMjQlMjAhJTIzJTFGJTIwMzMzLiUyMyUyMyUyNCUyNCUyNCUyMyUyMCElMjUlMUYlMjIlMjYhISUyMyUyMCElMkIlMkIlMkIlMjQlMjQlMjQoKCglMjQlMjAhJTI0JTIwISUyNCUyMCElMjUlMjAlMjAlMjYlMUYlMjMlNDAlMjAlNDAlMjQlMjAhJTI0ISEnJyczMzMlMjYlMjYlMjYlMjQlMjAhVVVVJTI0JTIwJTIwJTI1ISElMjMlMjAlMjAlMjMlMUYhJTIzJTFGISUyNSUyMCUyMCUyMyUxRiElMjMlMUYhJTIzJTIwISUyNCUyMCElMjQlMjAlMjAlMjQlMjAlMjIlMkIlMjIlMjIlMjQlMUYlMjAlMjQlMUYhJTIzJTIwJTIwJTI0JTIwJTIwJTIzJTFGISUyNSEhJTI0ISElMjUlMjAlMjAlMkIlMkIlMkIlMjYlMjAlMjAlMkIlMkIlMkIlMjMlMjAhJTI0JTFGJTIwJTI0JTFGJTIwJTI0JTIwJTIyJTI0ISEnJTIzJTIzJTI0JTIwISUyNSEhJTI0JTFGJTIwJTIzJTIwIS4uLiUyNCUxRiUyMCUyMyUxRiUyMCUyNSUyMCUyNSUyNCEhJyUyMyUyMyUyNCUyMCUyMCUyNCUyNCUyNCUyMyUxRiUyMCUyMyUxRiEpJTIzJTIzJTI0JTFGISUyNCUyMCUyMiUyNCUyMCElMjMlMjAhJTIzJTIwJTIwJTI2JTIyJTIyJTIzJTIwISUyNCUyMCUyMiUyMyUyMCUyMCUyNCUyMCUyMCUyNCEhJTI0JTIwJTIwJTI1JTFGJTIyJTI0JTIwITAlMjAwKCUyMiUyMiUyMyUyMCUyMiUyNCUxRiUyMiUyNCEhJTI0JTIwJTI0JTI2ISElMjQlMUYhJTI0JTIwISUyNSUyMCUyMiUyMyUyMCElMjQhISUyNCUyMCUyMCUyNCUyMCUyMCUyNCUyMCUyMCUyMyUyMCUyMCUyMyEhJTI1JTFGISUyMyEhJTI0JTFGJTIwJTI0JTFGJTI0JTIzISElMjQhISUyNiUyMCUyNiUyMyUyMCElMjQlMjAlMjAlMjQhISUyNCUyMCUyMCUyNCUxRiUyMCklMjIlMjIlMjMlMjAhJTI0JTIwJTIwJTI0ISElMjUlMjAlMjMlMjQlMjQlMjQlMjMlMUYhJTI0JTIwJTIwJTIzJTIwISUyMyUxRiElMjQlMUYhJTIzJTFGISclMjIlMjIlMjQlMjAlMjAlMjMlMjAhJTI0JTFGJTIwJTI0JTFGISUyMyUyMCUyMCUyNCEhJTIzJTFGJTIwJTI0JTIwJTIwJTI0JTIwJTIyJycnJTI0JTFGISUyNCUyMCElMjQhISUyMyUyMCUyMCUyMyUyMCElMjQlMUYhJTIzJTFGISUyMyUyMCUyMyUyNCUxRiElMjYlMjYlMjYlMjMlMjAlMjAlMjYhISUyNCUxRiElMjQlMjAlMjAlMjMlMjMlMjMlMjQlMjAlMjQlMjUhISUyNCUyMCElMjMlMjMlMjMnISElMjQhISUyNCUyMCUyMCUyNCUyMCUyMCUyNCUyNCUyNCUyNSUyMCUyMiglMjIlMjIlMjQlMjQlMjQlMjMlMjAlMjAlMjMlMjAlMjAlMjMlMjAlMjMlMjQhIScnJyUyNCUyNCUyNCUyNSEhJTI0JTIwJTIyJTIzJTIzJTIzJTI0JTIwISUyMyUyMCUyMikhISUyMyUyMCElMjQlMjIlMjIlMjMlMjAlMjAlMjYlMjIlMjIlMjYlMUYlMjIlMjQlMjAlMjAlMjMlMjMlMjMlMjQlMUYhJTIzISElMjQlMUYhJTI0JTFGISUyNCEhJTIzJTIwJTIwJTI2JTIwJTIzJTIzJTIwJTIyJTI0JTFGJTIwJTI1JTFGJTI1JTI1JTIwJTIwJTI0JTFGJTIwJTI0JTI0JTI0JTIzJTFGJTIzJTI1JTFGISUyNSUyMCUyMiUyMyUyMCUyMCUyNCUyMCElMjQlMjAhJTI0JTFGJTIwJTI1JTIwJTIwJTI0JTFGJTIwKCUyMCglMjQlMjAlMjAlMjMlMjAhJTI2JTFGJTIzJTI1JTIyJTIyJTI0JTIwISUyNCUyMCUyMCUyNCUxRiUyNCUyMyUxRiUyMCUxOCVFRiVCRiVCREElMTklMDAlMDAlMDAlRUYlQkYlQkR0Uk5TJTAwJUVGJUJGJUJEJUVGJUJGJUJEJTAxJTBGJUVGJUJGJUJEJTA0JUVGJUJGJUJEJTE4JTE0JTE3QyUwMiVFRiVCRiVCRC4lMTFyJTE5JUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTA5JUVGJUJGJUJEJUVGJUJGJUJEJTBBJTE2MiVFRiVCRiVCRFolMkYlRUYlQkYlQkQlMDYqJTEzJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEdlElMDglRUYlQkYlQkRGJTFBJTA1JTFCJUVGJUJGJUJEJTAzdyU3RCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRGclRUYlQkYlQkRzJUVGJUJGJUJEJUVGJUJGJUJERyVFRiVCRiVCRCUxRSVDRCU5NCVERiU4NiVFRiVCRiVCREVObyUxMl8lMEMlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkR5TSUzQiVFRiVCRiVCRCUzRSVFRiVCRiVCRCVFRiVCRiVCRCUwQiVENSVCRDAlNURCJUVGJUJGJUJEJTE1JUVGJUJGJUJEJUVGJUJGJUJEJTJDJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJENSVFRiVCRiVCRHAlRUYlQkYlQkRrJTdGUiVFRiVCRiVCRCUxMCUyNiVFRiVCRiVCRGolNUMlNDA2JUVGJUJGJUJEJUVGJUJGJUJEYSVEOSU4NSVFRiVCRiVCRCVDNyU5NiVFRiVCRiVCRCU1RSVFRiVCRiVCRHQlRUYlQkYlQkQxbSVFRiVCRiVCRCglRUYlQkYlQkQlRUYlQkYlQkRVJUVGJUJGJUJEJUVGJUJGJUJEJTI1JUVGJUJGJUJEJUQ2JThEJTYwJTIzJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTdCNCVFRiVCRiVCRCVFRiVCRiVCRCVFQyVBQyU5RlYlRUYlQkYlQkQlRUYlQkYlQkRxISVFRiVCRiVCRCVFRiVCRiVCRGQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkRQJUVGJUJGJUJEJTIyJUVGJUJGJUJEJTNEJUVGJUJGJUJEJUVGJUJGJUJEJTI0OCVFRiVCRiVCRCVFRiVCRiVCRCUxRCdjfiVFRiVCRiVCRCUyQlktJTA3JUVGJUJGJUJEJUVGJUJGJUJESCVFRiVCRiVCRCUwRCUwRXV4MyVFRiVCRiVCRCVFRiVCRiVCRCUxRiVFRiVCRiVCRCU1QiVFRiVCRiVCRCUzQ0olRUYlQkYlQkQlM0ElRUYlQkYlQkRsJUVGJUJGJUJEJUVGJUJGJUJEVCVFRiVCRiVCRFglRUYlQkYlQkQlRUYlQkYlQkQpNyVFRiVCRiVCRCUxQ0ElRUYlQkYlQkRoVyVFRiVCRiVCRCVFRiVCRiVCRG4lRUYlQkYlQkQlMjAlRUYlQkYlQkQlRUYlQkYlQkRJUyVFRiVCRiVCRCUzRjlNJTA2JUVGJUJGJUJEJUVGJUJGJUJEJTAwJTAwJTA0aklEQVR4JTVFJUVGJUJGJUJEJUVGJUJGJUJEUyVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCUwMkUlRUYlQkYlQkQlRUYlQkYlQkR+aiVEQSVCNiUxMXd3bCVEQiVCNiUzRCVFRiVCRiVCRDklRUYlQkYlQkQzJUVGJUJGJUJEbSVFRiVCRiVCRCUzRSVFRiVCRiVCRG0lRUYlQkYlQkRfcSVFRiVCRiVCRCU3Q1UlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkRIJTI1JUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJURBJUJCaiUwMyVFRiVCRiVCRCVFRiVCRiVCRGFBQSUyRiVFRiVCRiVCRFJXJUVGJUJGJUJEJUVGJUJGJUJEZyVFRiVCRiVCRCUxOSVFRiVCRiVCREMlRUYlQkYlQkRoJTA2JTVEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTI2JUVGJUJGJUJEMSVFRiVCRiVCRCVFRiVCRiVCRCUzRiVFRiVCRiVCREl0YSVFRiVCRiVCRCVFRiVCRiVCRHMlMTMlRUYlQkYlQkR0KSVFRiVCRiVCRDQlRUYlQkYlQkQuJUVGJUJGJUJEJUVGJUJGJUJEJTAzJUVGJUJGJUJEcSVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRGYlRUYlQkYlQkQlMjYlRUYlQkYlQkQtJUVGJUJGJUJEdyVFRiVCRiVCRGUlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQ5JUVGJUJGJUJEJURDJTk4JTNBJTNCJUVGJUJGJUJERiVFRiVCRiVCRCVFRiVCRiVCRCUxNiVFRiVCRiVCRCVFRiVCRiVCRHElMUElRUYlQkYlQkQlMEQ3JUVGJUJGJUJEJUVGJUJGJUJEVyVFRiVCRiVCRCVFRiVCRiVCRGZRJUVGJUJGJUJEJUVGJUJGJUJEJTNDJTIwdSVFRiVCRiVCRCVFRiVCRiVCRCVDRCU5RXglMTIlRUYlQkYlQkRGZyUxNSVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRFA5MTMlRUYlQkYlQkQlMDhxRSVFRiVCRiVCRG5PZyUwNiU0MGYlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkRBJUVGJUJGJUJEJUVGJUJGJUJEJTI1byVFRiVCRiVCRCUxQSVFRiVCRiVCRCUwNSVFRiVCRiVCRCVFRiVCRiVCRCUxMERSJTNFJTAyJUVGJUJGJUJEJTVFJTIzbiVFRiVCRiVCRCUwQiVFRiVCRiVCRElNJUVGJUJGJUJEJUVGJUJGJUJEdyU3RkRyJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTQwaSVFRiVCRiVCRCUxOSUwMCVFRiVCRiVCRCVFRiVCRiVCRCUwQyVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRG0lRUYlQkYlQkQlRUYlQkYlQkQlMUQlRUYlQkYlQkRrcGclRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkR0JTFERyVFRiVCRiVCRC0lRUYlQkYlQkQlMDEtJUVGJUJGJUJEJUVGJUJGJUJEJTNFV0MlRUYlQkYlQkRCOHAlMUQlMUJMSyVFRiVCRiVCRCUyQyVFRiVCRiVCRDYlMDIlRUYlQkYlQkQlRUYlQkYlQkR1ME0lMTMlRDklQTIlRUYlQkYlQkQlRUYlQkYlQkQlMUFzJUVGJUJGJUJEJTA4JUVGJUJGJUJEJTNFJUVGJUJGJUJEJTI1YSVFRiVCRiVCRCUwMm0lMDUlRUYlQkYlQkRyJUVGJUJGJUJEJTVEJUVGJUJGJUJESyVFRiVCRiVCRCUyRiVFRiVCRiVCRG4lRUYlQkYlQkQlMEQlRUYlQkYlQkQlRUYlQkYlQkRMRiVFQSU4MiVCQjUlRUYlQkYlQkQlMDQlM0R1JUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTNBJTAxWiVFRiVCRiVCRCVFRiVCRiVCRCUyRiVFRiVCRiVCRCVFRiVCRiVCRCUxQ1NLJTAxJUVGJUJGJUJEJUVGJUJGJUJEJTAzJUVGJUJGJUJEJUVGJUJGJUJEJUM5JUFDJUVGJUJGJUJEJUVGJUJGJUJEJTdGcCVFRiVCRiVCRDAlRUYlQkYlQkQlM0VUJUVGJUJGJUJEXyUwMyVFRiVCRiVCRCUwNiVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCUzQSVFRiVCRiVCRCVDNSVCMFMlMUYlRUYlQkYlQkQlRUYlQkYlQkR1LSUwRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRHclRUYlQkYlQkQlRUYlQkYlQkQlMjAlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlM0MlMEUlRUYlQkYlQkQ5aCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCUxNWklRUYlQkYlQkR6JTFGJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEZyVFRiVCRiVCRFclRUYlQkYlQkQ5JUVGJUJGJUJESSUyRmRXJTBFJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEOCUwQiUyMiUwMCVFRiVCRiVCRCVFRiVCRiVCRCUwQyglRUYlQkYlQkQlRUYlQkYlQkRJJUVGJUJGJUJETSUyQiVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCREklRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkRJJTNDZkIlMDMlRUYlQkYlQkQlRUYlQkYlQkQwJUVGJUJGJUJEKSVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRE4lRUYlQkYlQkQlRUYlQkYlQkQlMjZPJUVGJUJGJUJESCUwMCVGMiU5NiU4QyVBMFElRUYlQkYlQkQlMTglRUYlQkYlQkQlMDMlMUMlQzIlQUQlRUYlQkYlQkQlMDklRUYlQkYlQkQlRUYlQkYlQkQlMDl3JTAwJTNDJUVGJUJGJUJEMXhJXyUwNiUwNiVFRiVCRiVCREVSa20lMDRGJUVGJUJGJUJEJUVGJUJGJUJEJTI0JTA2TyVFRiVCRiVCRHIlRUYlQkYlQkRhJUVGJUJGJUJELiUwMiVFRiVCRiVCRCVFRiVCRiVCRCUxNyUzRSVFRiVCRiVCRCVFRiVCRiVCRCUzRSVFRiVCRiVCRCVEOCVCNiVFRiVCRiVCRCUwOSUwMyVFRiVCRiVCRCVFRiVCRiVCRGslRUYlQkYlQkQlRUYlQkYlQkQlN0NWJUVGJUJGJUJEJTEzJTA5JUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEV2FTJUVGJUJGJUJEJUMyJUExZiUxRiVFRiVCRiVCRCUxRSUzRlYlNjAlRUYlQkYlQkQlRUYlQkYlQkQlMDR6JUVGJUJGJUJEJTIwJTFFJUVGJUJGJUJEJTdGJTAwKSVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRG4lRUYlQkYlQkRQJURGJTg3JUVGJUJGJUJEdCUzRSVFRiVCRiVCRCVDQiU5NSVFRiVCRiVCRFElNUQlREQlQjIlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkRXJUVGJUJGJUJEbyVFRiVCRiVCRCVFRiVCRiVCRCUyNiVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCUwOEslRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlM0IlRUYlQkYlQkQlRUYlQkYlQkRkJUVGJUJGJUJEJTA2JUVGJUJGJUJEUSU1RCUwRiUwQyVFRiVCRiVCRFYlRUYlQkYlQkR1JTBGMEklRUYlQkYlQkQlMTQlRUYlQkYlQkQlRUYlQkYlQkREJUVGJUJGJUJEJTAyajQlMDYlRUYlQkYlQkQlRUYlQkYlQkQlMDYyJUVGJUJGJUJEJTFEJTBDJUVGJUJGJUJEJTVDaEslRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkR2JUNEJUEwQy0lRUYlQkYlQkQlN0I0JUVGJUJGJUJEJTExQTElRUYlQkYlQkQlRUYlQkYlQkR2JTNBJUVGJUJGJUJEJTA3RlNhJUVGJUJGJUJEJUVGJUJGJUJEJTBDaCVFRiVCRiVCREElRUYlQkYlQkRpJTBFJUVGJUJGJUJEJUVGJUJGJUJEYyUwRSVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRDMlRUYlQkYlQkQlMEUlRUYlQkYlQkQlRUYlQkYlQkR3JUVGJUJGJUJEJTA2JUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEaiUyNiUxRGolRUYlQkYlQkRFJUVGJUJGJUJELiUxNCUxMjdYJUVGJUJGJUJEJUVGJUJGJUJEZiVFRiVCRiVCRCVFRiVCRiVCRGd1UEMlRUYlQkYlQkQlMTAlRUYlQkYlQkQ3JUNEJTlGJUVGJUJGJUJEWCVFRiVCRiVCRCUxOVQlRUYlQkYlQkQlRUYlQkYlQkQlMEUlMDglRUYlQkYlQkQlRUYlQkYlQkQlNUIlMjQlRUYlQkYlQkQlMkMlNjAlRUYlQkYlQkQlRUYlQkYlQkQlNUUlRUYlQkYlQkQlMUIlMTglMUIlRUYlQkYlQkRDJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEMFklMDclRUYlQkYlQkRzaiUzRCVFRiVCRiVCRGklRUYlQkYlQkQlMjUlMkYlRUYlQkYlQkQlMDEqSiVFRiVCRiVCRCVFRiVCRiVCRG8lMTAlRUYlQkYlQkROJUVGJUJGJUJEJTExJUVGJUJGJUJEJTBGOCVGMSVBMyU4RCVCRmolRUYlQkYlQkQ3JTBEJTI1TCUxRCVFRiVCRiVCRClMJUVGJUJGJUJEJTE2JUVGJUJGJUJEJTE0UiVFRiVCRiVCRHolRUYlQkYlQkR0eSpJJUVGJUJGJUJEJUVGJUJGJUJEZSUxNSUwMCUxMyVFRiVCRiVCRCUwMyUzQiVFRiVCRiVCRCdwJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEZyVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRGclRUYlQkYlQkQlNUQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlMkMlM0MlRUYlQkYlQkQlMDMlRUYlQkYlQkQlRUYlQkYlQkQlMUElMERSJTE2JTI1JUVGJUJGJUJEJUVGJUJGJUJEJUVBJTk5JUEwJTJGc0QlMUIlM0ZMKCVFRiVCRiVCRGQlRUYlQkYlQkR0JUVGJUJGJUJEJUVGJUJGJUJEJTNFJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTI1JUVGJUJGJUJEJUVGJUJGJUJEJTA3anUlRUYlQkYlQkQlRUYlQkYlQkQlMDAlRUYlQkYlQkQ3NCVFRiVCRiVCRCVFRiVCRiVCREdyJUVGJUJGJUJEJTVFdiVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCUwNyUyMyUwRSVFRiVCRiVCRGclRUYlQkYlQkRxJUVGJUJGJUJERiVFRiVCRiVCRG0lRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlN0QlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlMEQwSSVFRiVCRiVCRCUxNSVFRiVCRiVCRCVFRiVCRiVCRCUwQiVFRiVCRiVCRCUwNyVFRiVCRiVCRCVFRiVCRiVCRG8lMDA5JUVGJUJGJUJEISVFRiVCRiVCRCUxRlZrJTIybyVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRE4lRUYlQkYlQkQlMjUlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkRlJTFBJUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTFBJTNERCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCUwQSVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRCU0MCVFRiVCRiVCRF91JUVGJUJGJUJEJUVGJUJGJUJEJTAwJUVGJUJGJUJEJTI1JUVGJUJGJUJEJTFFYiVFRiVCRiVCRDYlMTclMDElRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkRnJTQwJUVGJUJGJUJEJyVFRiVCRiVCRCU3RCVFRiVCRiVCRCUwQyUxMCVERSVCQSVFRiVCRiVCRCU0MCVFQiU5MiU4N0dWJUVGJUJGJUJELSVFRiVCRiVCRCVFRiVCRiVCREUoJTFDJUVGJUJGJUJEJUVGJUJGJUJEQiVFRiVCRiVCRHYlRUYlQkYlQkRCJTFDY0clMURMJUVGJUJGJUJEJTdGNTAlMURaJTFFJUVGJUJGJUJEJTVEJUNBJUJGJTBFJUVGJUJGJUJEJTE5JTI2JTBFJUVGJUJGJUJEJUVGJUJGJUJEOCVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRG0lRUYlQkYlQkRLJUVGJUJGJUJEJTNBRSVFRiVCRiVCRCVFRiVCRiVCREIlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlNUMlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQ0VyVFRiVCRiVCRCVFRiVCRiVCRCUyMiUyRiVFRiVCRiVCRCVFRiVCRiVCRFolRUYlQkYlQkQlRUYlQkYlQkQlRUYlQkYlQkQlMTYlRUYlQkYlQkQlMDMlRUYlQkYlQkRNdCVFRiVCRiVCRCVFRiVCRiVCRFglMUUhWSVERiVBMSU3QiVFRiVCRiVCRHYlMEYlRUYlQkYlQkQlRUYlQkYlQkR4JUVGJUJGJUJEJUVGJUJGJUJEVSVFRiVCRiVCRDAlRUYlQkYlQkQlN0R0JUVGJUJGJUJEJTE3XyVFRiVCRiVCRCVFRiVCRiVCREFmJUVGJUJGJUJEbUl0JUVGJUJGJUJEJUVGJUJGJUJEJUVGJUJGJUJEJTVFeSVFRiVCRiVCRCVFRiVCRiVCRCVFRiVCRiVCRDglRUYlQkYlQkQlMUYlMUIlRUYlQkYlQkRWRCVFRiVCRiVCRCVFRiVCRiVCRFklRUYlQkYlQkQlMDAlMDAlMDAlMDBJRU5EJUVGJUJGJUJEQiU2MCVFRiVCRiVCRA==0';
    return `data:image/png;base64,${dummy2}`}

  // const content2url2 = async (content) => {
  //   const reader = new FileReader();
  //   reader.readAsDataURL(content);
  //   reader.onloadend = 
  //   return url
  // }


  const onDownloadPressed = async () => {
    const content = await downloadFromDDC(cid);
    digestMessage(content)
    .then(digestBuffer => console.log(digestBuffer));
    // const url = URL.createObjectURL(new File([content]));
    // const link = document.createElement('a');
    // link.href = url;
    // link.setAttribute('download', `Filename.png`);
    // document.body.appendChild(link);
    // link.click();
    
    //debugger
    //var blob = new Blob([content], {type: "image/png"});
    //var base64 = btoa(content.toString());
    //var base64 = btoa(unescape(encodeURIComponent(content)));
    //var base64 = content.toString('base64')
    //ovar url = `data:${base64}`;
    //var url = "data:image/png;base64," + (base64)
    //var url = URL.createObjectURL(blob);
    //console.log(url)
    
    
    //const p2 = URL.createObjectURL(content);
    //console.log('p2', p2);
    setImage(content2url(content));
    //console.log(content);

    //console.log(content);
    //console.log(content);

    //setStatus(`Downloaded. Here's your content: ${content}`);
    setStatus(`Downloaded.`);
    //console.log(content);
}

const handleChange = (event) => {
  const selectedFile = event.target.files[0];
  setUploadData(selectedFile);
  console.log('1', selectedFile);
  setFile(selectedFile);
  const filePreview = URL.createObjectURL(selectedFile);
  //console.log(filePreview);
  //setPreview(filePreview);
  //selectedFile.text().then(content => setPreview(content2url(content)))
  selectedFile.text().then(content => {
    console.log("upload length: ", content.length);
    setPreview(content2url(content))
    }) 
  console.log('preview', preview);
}



  return (   
    <div className="Main">
      <br></br>
      <button id="walletButton" onClick={connectWalletPressed}>
        {walletAddress.length > 0 ? (
          "Connected: " + String(walletAddress).substring(0, 6) + "..." + String(walletAddress).substring(38)
        ) : (
          <span>Connect Wallet</span>
        )}
      </button>
      <br></br>
      <h1 id="title"> Create an NFT with Cere Freeport and DDC </h1>

      <div class="header">
        <h3>Status message:</h3>
      <p id="status"> {status} </p>
      {/* <p>{preview}</p> */}
      <img src={image} />
      
      </div>

      <br></br>
      <h2> Upload content to DDC </h2>
      {file && <img src={preview} alt={file.name} style={{width: "200px"}}></img>}
      <br></br>
      <form class="form" id="myform">
      {/* <input type="file" id="inpFile" onChange={(event) => setUploadData(event.target.files[0])}></input> */}
      <input type="file" id="inpFile" onChange={(event) => handleChange(event)}></input>
      </form>
      {/* <input type="text" placeholder="Enter content to upload to DDC. (e.g., a random string)" onChange={(event) => setUploadData(event.target.value)}/> */}
      &nbsp;
      <input type="text" placeholder="Give your content a title." onChange={(event) => setUploadDataTitle(event.target.value)}/>
      &nbsp;
      <input type="text" placeholder="Give your content a description." onChange={(event) => setUploadDataDescription(event.target.value)}/>


      <button id="actionButton" onClick={onUploadPressed}> Upload </button>      

      <br></br><br></br>
      &nbsp;
      <h2> Now download that content from DDC </h2>
      <input type="text" placeholder="Enter content ID returned from upload step." onChange={(event) => setCid(event.target.value)}/>
      <button id="actionButton" onClick={onDownloadPressed}> Download </button>      


      <br></br><br></br>
      &nbsp;
      <h2> Mint an NFT with Freeport </h2>
      <input type="text" placeholder="Enter some token metadata." onChange={(event) => setMetadata(event.target.value)}/>
      &nbsp;
      <input type="number" placeholder="Enter the number of copies to mint." value={qty} onChange={(event) => setQty(event.target.value)}/>
      <button id="actionButton" onClick={onMintPressed}> Mint NFT</button>      
    </div>
  );
};

export default Main;